### PR TITLE
argparse code review implementation closes #16

### LINKED ISSUE #16: argparse code review changes
https://github.com/alta3/ssh-githugger/blob/03185a82b321a4578f84fefb3061e477d57fc48b/ssh-githugger.py#L10

`source_user` key becomes `source_users`
`metavar` value becomes  `source_users`

```
Metavar: It provides a different name for optional argument in help messages. Provide a value for the metavar keyword argument within add_argument().

>>> parser = argparse.ArgumentParser()
>>> parser.add_argument('--foo', metavar='YYY')
>>> parser.add_argument('bar', metavar='XXX')
>>> parser.parse_args('X --foo Y'.split())
Namespace(bar='X', foo='Y')
>>> parser.print_help()
usage:  [-h] [--foo YYY] XXX

positional arguments:
  XXX

optional arguments:
  -h, --help  show this help message and exit
  --foo YYY
```

### PR DESCRIPTION
**Pull request by sfeeser**
Closes #16

### CODE REVIEW

**Comment by bryfry** [comment]
Let's make `-t` the same as all the others in that it will actually take the value it holds, not just the environment variable key. This will keep all the flags constant. Here's why that is different from what we discussed last night:

- As a user running this script from the cli I want to be able to provide parameters for any/all functionality without switching to env_vars
- Every cli argument should have a complementary env_var (documented in it's help line) 
- If both are provided (cli flag and ENV) the environment should win
- Our service based invocations should only use env vars, not flags

**Review by bryfry — CHANGES_REQUESTED** [review]
Let's make `-t` the same as all the others in that it will actually take the value it holds, not just the environment variable key. This will keep all the flags constant. Here's why that is different from what we discussed last night:

- As a user running this script from the cli I want to be able to provide parameters for any/all functionality without switching to env_vars
- Every cli argument should have a complementary env_var (documented in it's help line) 
- If both are provided (cli flag and ENV) the environment should win
- Our service based invocations should only use env vars, not flags

**Comment by sfeeser** [comment]
How to read envs into python
https://github.com/alta3/enchilada/blob/668ede66e732aa00380dcb5066a7ea5a14bdd795/bouncer/admin/utils.py#L13

**Review by bryfry — APPROVED** [review]
LGTM 👍

**Pull request merged**
